<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Tags with multilingual slugs and SEO content
        Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->string('slug')->unique(); // Base English slug
            $table->string('name'); // Display name
            $table->string('category')->nullable(); // body, ethnicity, age, etc.
            $table->integer('models_count')->default(0);
            $table->boolean('is_featured')->default(false);
            $table->integer('sort_order')->default(0);
            $table->timestamps();
            
            $table->index(['category', 'models_count']);
            $table->index('is_featured');
        });

        // Tag translations (slugs + SEO content per language)
        Schema::create('tag_translations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tag_id')->constrained()->onDelete('cascade');
            $table->string('locale', 10); // en, es, fr, de, pt, it, zh-TW, etc.
            $table->string('slug'); // Translated slug
            $table->string('name'); // Translated name
            $table->string('meta_title')->nullable();
            $table->text('meta_description')->nullable();
            $table->text('page_content')->nullable(); // SEO content for tag page
            $table->timestamps();
            
            $table->unique(['tag_id', 'locale']);
            $table->unique(['locale', 'slug']);
            $table->index('locale');
        });

        // Countries with translations
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('code', 2)->unique(); // ISO 3166-1 alpha-2
            $table->string('slug')->unique();
            $table->string('name');
            $table->string('flag', 10)->nullable(); // Emoji flag
            $table->integer('models_count')->default(0);
            $table->timestamps();
            
            $table->index('models_count');
        });

        // Country translations
        Schema::create('country_translations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('country_id')->constrained()->onDelete('cascade');
            $table->string('locale', 10);
            $table->string('slug');
            $table->string('name');
            $table->string('meta_title')->nullable();
            $table->text('meta_description')->nullable();
            $table->text('page_content')->nullable();
            $table->timestamps();
            
            $table->unique(['country_id', 'locale']);
            $table->unique(['locale', 'slug']);
        });

        // Model FAQs (generated by AI, editable)
        Schema::create('model_faqs', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('cam_model_id');
            $table->string('locale', 10)->default('en');
            $table->string('question');
            $table->text('answer');
            $table->integer('sort_order')->default(0);
            $table->timestamps();
            
            $table->index(['cam_model_id', 'locale']);
        });

        // Model SEO content (descriptions, meta, etc.)
        Schema::create('model_seo_content', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('cam_model_id');
            $table->string('locale', 10)->default('en');
            $table->string('meta_title')->nullable();
            $table->text('meta_description')->nullable();
            $table->text('long_description')->nullable();
            $table->text('custom_content')->nullable(); // Rich editor content
            $table->timestamps();
            
            $table->unique(['cam_model_id', 'locale']);
        });

        // Site-wide translations cache
        Schema::create('translations_cache', function (Blueprint $table) {
            $table->id();
            $table->string('key'); // Original text or key
            $table->string('locale', 10);
            $table->text('value'); // Translated text
            $table->string('context')->nullable(); // seo, ui, content
            $table->timestamps();
            
            $table->unique(['key', 'locale']);
            $table->index('locale');
        });

        // Supported locales configuration
        Schema::create('supported_locales', function (Blueprint $table) {
            $table->id();
            $table->string('code', 10)->unique(); // en, es, fr, zh-TW
            $table->string('name'); // English, Spanish, French
            $table->string('native_name'); // English, Español, Français
            $table->string('flag', 10)->nullable();
            $table->boolean('is_active')->default(true);
            $table->boolean('is_default')->default(false);
            $table->integer('sort_order')->default(0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('supported_locales');
        Schema::dropIfExists('translations_cache');
        Schema::dropIfExists('model_seo_content');
        Schema::dropIfExists('model_faqs');
        Schema::dropIfExists('country_translations');
        Schema::dropIfExists('countries');
        Schema::dropIfExists('tag_translations');
        Schema::dropIfExists('tags');
    }
};
